version: '3.1'

volumes:
  pg_comment:

services:
  comment_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1122
      - POSTGRES_DB=comment_db
    volumes:
      - pg_comment:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  app:
    restart: always
    build: .
    ports:
      - "80:80"
    depends_on:
      - comment_db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://comment_db:5432/comment_db"
      JAVA_OPTS: '-Xmx512m'