volumes:
  postgres_volume:

services:
  postgres_release_comment_database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1122
      - POSTGRES_DB=comment_database
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  app:
    restart: always
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres_release_comment_database
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_release_comment_database:5432/comment_database"
      JAVA_OPTS: '-Xmx512m'